# Generated by Django 6.0.4 on 2026-05-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_alter_realtors_lic_img_alter_realtors_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtors',
            name='lic_img',
            field=models.ImageField(blank=True, null=True, upload_to='realtorpic/'),
        ),
        migrations.AlterField(
            model_name='realtors',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
