# Generated by Django 6.0.4 on 2026-05-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_alter_realtors_lic_img_alter_realtors_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtors',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
