# Generated by Django 6.0.4 on 2026-05-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_alter_realtors_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquriy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField()),
                ('description', models.TextField()),
            ],
        ),
    ]
