# Generated by Django 6.0.4 on 2026-05-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0006_enquriy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enquriy',
            new_name='Enquiry',
        ),
    ]
