# Generated by Django 6.0.4 on 2026-05-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='bookiing_date',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='property_dtd',
            new_name='property_detail',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='advance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='token',
            field=models.IntegerField(default=0),
        ),
    ]
