# Generated by Django 6.0.4 on 2026-05-26 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_bookiing_date_bookingmodel_booking_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='property_detail',
            new_name='property_dtd',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='area',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='owner_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='property_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='rent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='advance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='token',
            field=models.IntegerField(),
        ),
    ]
