# Generated by Django 6.0.4 on 2026-05-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_property_detail_bookingmodel_property_dtd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='property_dtd',
            new_name='property_detail',
        ),
    ]
