# Generated by Django 6.0.4 on 2026-05-29 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_property_dtd_bookingmodel_property_detail'),
        ('properties', '0011_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_party_name', models.CharField(max_length=100)),
                ('owner_phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('stamp_papper_price', models.IntegerField(choices=[(20, 20), (50, 50), (100, 100), (200, 200), (300, 300)])),
                ('secondary_party_name', models.CharField(max_length=100)),
                ('secondary_phone', models.BigIntegerField()),
                ('secondart_email', models.EmailField(max_length=254)),
                ('secondary_address', models.CharField(max_length=100)),
                ('advance_amount', models.IntegerField()),
                ('property_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.allproperties')),
            ],
        ),
    ]
