# Generated by Django 6.0.4 on 2026-05-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='secondary_address',
            field=models.TextField(),
        ),
    ]
