# Generated by Django 6.0.4 on 2026-05-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allproperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('BUY', 'buy'), ('SELL', 'sell'), ('RENTAL', 'rental'), ('LEASE', 'lease')])),
                ('price', models.IntegerField()),
                ('floors', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('1STORY', '1story'), ('2STORY', '2story'), ('3STORY', '3story'), ('DUPLEX', 'duplex'), ('INDIVIDUAL', 'individual'), ('APARTMENT', 'apartment')])),
                ('age', models.IntegerField()),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('no_of_rooms', models.IntegerField()),
                ('no_of_bathrooms', models.IntegerField()),
                ('balcony', models.BooleanField()),
                ('attached_bathroom', models.BooleanField()),
                ('owner_name', models.CharField(max_length=100)),
                ('property_image', models.ImageField(blank=True, null=True, upload_to='media/images/')),
            ],
        ),
    ]
