# Generated by Django 6.0.4 on 2026-05-12 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_alter_realtors_photo'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproperties',
            name='realtorname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='realtorss', to='formapp.realtors'),
            preserve_default=False,
        ),
    ]
