# Generated by Django 6.0.4 on 2026-05-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_allproperties_realtorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproperties',
            name='verdict',
            field=models.CharField(choices=[('soldout', 'SOLDOUT'), ('pending', 'PENDING')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
