# Generated by Django 6.0.4 on 2026-05-20 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_allproperties_verdict'),
    ]

    operations = [
        migrations.CreateModel(
            name='balcony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balcony_pics', models.ImageField(blank=True, null=True, upload_to='balcony/')),
                ('rproperits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baallproperties', to='properties.allproperties')),
            ],
        ),
        migrations.CreateModel(
            name='bathroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bath_pics', models.ImageField(blank=True, null=True, upload_to='bathroom/')),
                ('rproperits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballproperties', to='properties.allproperties')),
            ],
        ),
        migrations.CreateModel(
            name='kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_pics', models.ImageField(blank=True, null=True, upload_to='kitchen/')),
                ('rproperits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kallproperties', to='properties.allproperties')),
            ],
        ),
        migrations.CreateModel(
            name='Livingarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_pics', models.ImageField(blank=True, null=True, upload_to='livingarea/')),
                ('lproperits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lallproperties', to='properties.allproperties')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_pics', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('rproperits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rallproperties', to='properties.allproperties')),
            ],
        ),
    ]
