# Generated by Django 6.0.4 on 2026-05-21 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_balcony_bathroom_kitchen_livingarea_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('EMI', 'Book With EMI'), ('ADVANCE', 'Book Advance')], max_length=20)),
                ('loan_amount', models.FloatField(blank=True, null=True)),
                ('tenure', models.IntegerField(blank=True, null=True)),
                ('emi_amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.allproperties')),
            ],
        ),
    ]
