# Generated by Django 6.0.4 on 2026-05-23 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertybooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('water', models.IntegerField(default=1000)),
                ('maintainence', models.IntegerField(default=500)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varea', to='properties.allproperties')),
                ('property_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vname', to='properties.allproperties')),
            ],
        ),
    ]
