# Generated by Django 6.0.4 on 2026-05-24 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_visit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.allproperties'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='property_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
