# Generated by Django 6.0.4 on 2026-05-26 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='property_name',
            new_name='user',
        ),
    ]
