# Generated by Django 6.0.4 on 2026-05-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_rename_property_name_visit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
