# Generated by Django 6.0.4 on 2026-05-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_book_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
